### PR TITLE
fix: implement drag and drop between multiple rows plugins

### LINKED ISSUE #188: plugin-rows: improve dnd
- Larger drop area (especially on left side since the drag handler is outside of the usual div)
- Handle larger documents (e.g. by restricting the preview's height)
- Sometimes it seems like the dnd doesn't work correctly (e.g. moves many documents around...)

### PR DESCRIPTION
**Pull request by Knorrke**
## Fixed
**plugin-rows**: Support drag and drop between multiple rows plugins and improve UX

fixes #188
Larger drop zone: dnd-zone
Drag and drop between plugins: dnd-multiple-plugins

### CODE REVIEW

**Comment by inyono** [comment]
- [ ] Blur before dragging and focus after?
- [ ] Check focus tree if it makes sense to drag (in itself, same position, ...)

File: packages/plugins/rows/src/editor/render.tsx [hunk 1]
```diff
@@ -272,26 +323,76 @@ export function RowRenderer({
...
+    )
+    if (dragIndex === -1 || dropZoneIndex === -1) {
+      // different parent
+      return false
+    }
+    // check that its not the same position
+    return draggingAbove
+      ? dropZoneIndex - 1 !== dragIndex
+      : dropZoneIndex + 1 !== dragIndex
+  }
```
Comment (Knorrke) [inline packages/plugins/rows/src/editor/render.tsx]: @inyono any ideas of refactoring this to make it clearer what's happening?

Comment (inyono) [reply packages/plugins/rows/src/editor/render.tsx]: Done

**Comment by inyono** [comment]
I made a couple of improvements (in my opinion 😅) in both code and behaviour. Please review if you are okay with the changes.

Build fails because API Extractor gets confused by some types. Gonna fix that and simplify the state types TS types.

File: packages/plugins/rows/src/editor/use-can-drop.ts [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+    return focusPath.includes(dragId)
+  }
+
+  function wouldDropAtInitialPosition(dragId: string) {
+    const focusTree = getFocusTree()(store.getState())
+    if (!focusTree) return true
+    const parent = findParent(focusTree, dragId)
+
+    const dropIndex = getChildPosition(parent, id)
+    if (dropIndex === null) return true
```
Comment (Knorrke) [inline packages/plugins/rows/src/editor/use-can-drop.ts]: This needs to return false, because the check means the dropZone doesn't have the same parent as the dragged element. So it definitely is not in the same position. Maybe also add a comment, since that's not really clear by looking at the code.

Comment (inyono) [reply packages/plugins/rows/src/editor/use-can-drop.ts]: Done
